;Eric Zhou, ezzhou
(require 2htdp/image)

;(1.)
;(a.)
(* (- (* 7 3) (- 8 (string-length (string-append "CS" "1101")))) (/ 32 16))
;(* (- 21 (- 8 (string-length (string-append "CS" "1101")))) (/ 32 16))
;(* (- 21 (- 8 (string-length CS1101))) (/ 32 16))
;(* (- 21 (- 8 6)) (/ 32 16))
;(* (- 21 2) (/ 32 16))
;(* 19 (/ 32 16))
;(* 19 2)
;38

;(b.)
;Helper Methods:
(define (triple n)
  (* n 3))

(if (> (triple 2) (triple (/ 12 4))) (sqrt (+ 4 (* 15 4))) 107)
;(if (> 6 (triple (/ 12 4))) (sqrt (+ 4 (* 15 4))) 107)
;(if (> 6 (triple 3)) (sqrt (+ 4 (* 15 4))) 107)
;(if (> 6 9) (sqrt (+ 4 (* 15 4))) 107)
;(false (sqrt (+ 4 (* 15 4))) 107)
;107

;(2.)
;four-square: Image -> Image
;Purpose: To create a 4-tiled image of the original

;;(define WPIGOAT .)

(define (four-square image)
  (above
    (beside(flip-horizontal image) image)
    (beside(flip-vertical (flip-horizontal image)) (flip-vertical image))))

;;(four-square WPIGOAT)

;(3.)
;cost: Number -> Number
;Purpose: Produces the cost to hold an event depending on the number of attendees
(define (cost attendees)
  (+ 1500 (* 2 attendees)))

(check-expect (cost 100) 1700)

;income: [Number, Number] -> Number
;Purpose: Produces the income generated by ticket sales based on the number of attendees and the price per ticket
(define (income attendees ticket-cost)
  (* attendees ticket-cost))

(check-expect (income 300 49.95) 14985)

;profit: [Number, Number] -> Number
;Purpose: Calculates the profit of the event based on the number of attendees and the price per ticket
(define (profit attendees ticket-cost)
  (- (income attendees ticket-cost) (cost attendees)))

(check-expect (profit 200 19.99) 2098)

;(4.)
;Constants:
(define INTEREST 0.04)
(define LOAN-PERIOD 30)
(define EXTRA-BANK-FEES 1000)

;Helper Methods:
(define (calculate-principal home-price down-payment)
  (- home-price down-payment))
         
;Signature: [Number, Number] -> Number
;Purpose: Calculate the grand total paid for a house given the purchase price and the initial payment(down payment)
(define (total-house-cost home-price down-payment)
  (+ home-price (* INTEREST (calculate-principal home-price down-payment) LOAN-PERIOD) EXTRA-BANK-FEES))

(check-expect (total-house-cost 1500000 300000) 2941000)
